### PR TITLE
Packages was misspelled

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by hadley** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
De nada.  This could be useful in trying to get a more programmatic and controlled handle on conflicts.

But you should rename it.  This is no longer R, this is becoming TV.  

And people will be able to say _"as I did on TV..."_

**Comment by hadley** [comment]
And then the official tidyverse blog can be called "as seen on tv"

**Comment by eddelbuettel** [comment]
Nothing but upside.

**Pull request merged**
